# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClassCoordinatorExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action', '~> 4.2.0'
  pod 'RxDataSources', '~> 4.0.1'
  pod 'OAuthSwift'
  # Pods for ClassCoordinatorExample

  target 'ClassCoordinatorExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClassCoordinatorExampleUITests' do
    # Pods for testing
  end

end
