# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HPCounter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HPCounte
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  target 'HPCounterTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest'
    pod 'RxNimble/RxTest'
  end

  target 'HPCounterUITests' do
    # Pods for testing
  end

end
