# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MemeGen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MemeGen
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'MemeGenTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest'
    pod 'Quick'
    pod 'Nimble'
  end

  target 'MemeGenUITests' do
    # Pods for testing
  end

end
