# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubTDD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubTD
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwiftLint'
  pod 'RxDataSources'
  pod 'SnapKit'

  target 'GitHubTDDTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
    pod 'Cuckoo'
  end

  target 'GitHubTDDUITests' do
    # Pods for testing
  end

end
