# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokemonExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Nuke'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'SnapKit'
  # Pods for PokemonExample

  target 'PokemonExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokemonExampleUITests' do
    # Pods for testing
  end

end
