# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RepoSearchTDD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "RxSwift"
  pod "RxCocoa"
  pod "SnapKit"
 
  # Pods for RepoSearchTDD

  target 'RepoSearchTDDTests' do
    inherit! :search_paths
    # Pods for testing
  pod "RxTest"
  pod "RxBlocking"

  end

  target 'RepoSearchTDDUITests' do
    # Pods for testing
  end

end
