# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SideDishExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'RxViewController'
  pod 'Alamofire'
  pod 'RxBlocking'
  pod 'SnapKit'
  # Pods for SideDishExample
end

target 'SideDishExampleTests' do
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'RxViewController'
  pod 'Alamofire'
  pod 'RxBlocking'
  
end
