# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactorBlog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactorBlo
  pod 'ReactorKit'
  
  # UI
  pod 'SnapKit'
  pod 'DropDown'
  
  # Rx
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  pod 'RxViewController'
  pod 'RxGesture'
  pod 'RxFlow'
  
  # Network
  pod 'Moya/RxSwift'
  pod 'Kingfisher'
  
  # Tool
  pod 'Then'
  pod 'ReusableKit/RxSwift'

  target 'ReactorBlogTests' do
    inherit! :search_paths
    # Pods for testin
    pod 'Nimble'
    pod 'RxTest'
    pod 'RxExpect'
  end

  target 'ReactorBlogUITests' do
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
	   config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
	    config.build_settings['ARCHS'] = 'arm64 x86_64'
	    config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end




end
